SET SQL_SAFE_UPDATES = 0;
USE `prueba-vocacional` ;

/* insercion de datos en la tabla de "conclusiones" */
DELETE FROM `prueba-vocacional`.`conclusiones`
WHERE concl_status = 'A';

/* insercion de datos en la tabla de "conclusiones" -> Area "Intereses" */

INSERT INTO `prueba-vocacional`.`conclusiones`(concl_id, concl_1cat_id, concl_2cat_id, concl_explicacion, concl_texto, concl_area, concl_status)VALUES 

(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'EP' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'SS' AND cat_area = 'I'),NULL, 'Ciencias Políticas y Administración Pública. Relaciones Internacionales, Ciencias de la Comunicación, Sociología, Derecho, Trabajo Social, Economía, Pedagogía, Enseñanza de Inglés, Psicología, Enfermería y Obstetricia, Odontología, Optometría.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'EP' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'V' AND cat_area = 'I'),NULL, 'Relaciones Internacionales, Derecho, Letras Clásicas, Lengua y Literaturas Hispánicas, Literatura Dramática y Teatro, Lengua y Literaturas Modernas, Bibliotecología y Estudios de la Información, Enseñanza de Inglés, Ciencias de la Comunicación, Ciencias Políticas y Administración Pública.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'EP' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'AP' AND cat_area = 'I'),NULL, 'Diseño Gráfico, Diseño y Comunicación Visual, Urbanismo, Diseño Industrial, Literatura Dramática y Teatro.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'EP' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'MS' AND cat_area = 'I'),NULL, 'Etnomusicología, Piano, Canto, Instrumentista, Composición, Educación Musical.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'EP' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'OG' AND cat_area = 'I'),NULL, 'Actuaría, Economía, Administración, Informática, Ciencias Políticas y Administración Pública, Relaciones Internacionales, Planificación para el Desarrollo Agropecuario, Geografía, Contaduría, Ingeniería en Alimentos, Quimica Industrial.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'V' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'SS' AND cat_area = 'I'),NULL, 'Ciencias de la Comunicación, Derecho, Ciencias Políticas y Administración Pública, Estudios Latinoamericanos, Letras Clásicas, Lengua y Literaturas Hispánicas,  Literatura Dramática y Teatro, Lengua y Literatura Modernas, Enseñanza de Inglés, Bibliotecología y Estudios de la Información.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'V' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'MS' AND cat_area = 'I'),NULL, 'Composición, Educación Musical, Canto.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'V' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'OG' AND cat_area = 'I'),NULL, 'Bibliotecología y Estudios de la Información, Relaciones Internacionales, Ciencias Políticas y Administración Pública, Sociología, Estudios Latinoamericanos.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'AP' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'SS' AND cat_area = 'I'),NULL, ' Artes Visuales, Diseño Gráfico, Diseño y Comunicación Visual, Urbanismo, Arquitectura del Paisaje, Arquitectura, Diseño Industrial.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'MS' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'SS' AND cat_area = 'I'),NULL, 'Composición, Instrumentista, Piano,Educación Músical, Canto, Etnomusicología.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'CI' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'SS' AND cat_area = 'I'),NULL, 'Ingeniería en Alimentos, Investigación Biomédica Básica, Ciencias Genómicas, Optometría, Química en Alimentos, Química Farmacéutico- Biológica, Biología, Odontología, Medicina Veterinaria y Zootecnia, Medicina, Enfermería y Obstetricia, Psicología, Ciencias Políticas y Administración Pública, Sociología, Trabajo Social, Historia, Pedagogía, Estudios Latinoamericanos, Filosofía.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'CI' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'EP' AND cat_area = 'I'),NULL, 'Medicina, Medicina Veterinaria y Zootecnia, Física, Química, Biología, Ciencias Genómicas, Investigación Biomédica Básica, Enfermería, Psicología, Estudios Latinoamericanos, Pedagogía, Optometría.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'CI' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'AP' AND cat_area = 'I'),NULL, 'Odontología, Urbanismo, Arquitectura, Diseño Industrial.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'MC' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'CL' AND cat_area = 'I'),NULL, 'Arquitectura, Diseño Industrial, Física, Ingenierías: Civil, en Computación, Geofísica, Mecánica Eléctrica, de Minas y Metalurgia, Petrolera, Topográfica y Geodésica, en Telecomunicaciones, Mecánica y Mecatrónica.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'AL' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'SS' AND cat_area = 'I'),NULL, 'Ingeniería Agrícola, Ingeniería Petrolera, Sociología, Planificación para el Desarrollo Agropecuario, Trabajo Social, Medicina Veterinaria y Zootecnia, Biología, Arquitectura de Paisaje.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'AL' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'EP' AND cat_area = 'I'),NULL, 'Ingeniería Petrolera, Planificación para el Desarrollo Agropecuario, Trabajo Social, Ingeniería Agrícola, Medicina Veterinaria y Zootecnia, Ingeniería Civil, Arquitectura, Urbanista.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'AL' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'AP' AND cat_area = 'I'),NULL, 'Arquitectura, Urbanismo, Arquitectura de Paisaje, Artes Visuales.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'AL' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'OG' AND cat_area = 'I'),NULL, 'Ingeniería Agrícola, Geografía, Planificación para el Desarrollo Agropecuario, Biología, Medicina Veterinaria y Zootencnia.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'AL' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'CI' AND cat_area = 'I'),NULL, 'Ingenierías: Agrícolas, Geológica, Petrolera, de minas y Metalurgia, Geografía, Planificación para el Desarrollo Agropecuario, Biología, Medicina Veterinaria y Zootecnica, Ciencias Ambientales, Manejo de Zonas Costeras.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'AL' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'CL' AND cat_area = 'I'),NULL, 'Arquitectura, Urbanismo, Arquitectura de Paisaje, Ingenierías: Agrícola, Civil, Geológica, Mecánica Eléctrica, de Minas y Metalurgia, Petrolera, Topográfica y Geodésica, Química Metalúrgica y Telecomunicaciones.', 'I', 'A'), 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'AL' AND cat_area = 'I'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'MC' AND cat_area = 'I'),NULL, 'Ingierías: Civil, Industrial, Mecánica Eléctrica, Petrolera, Topográfica y Geodésica, de Minas y Metalurgia, Geofísica, Geológica y Telecomunicaciones.', 'I', 'A');

/* insercion de datos en la tab la "Conclusiones" -> Area "Aptitudes" */

INSERT INTO `prueba-vocacional`.`conclusiones`(concl_id, concl_1cat_id, concl_2cat_id, concl_explicacion, concl_texto, concl_area, concl_status)VALUES 
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'SS' AND cat_area = 'A'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'SS' AND cat_area = 'A'), 'Preferencia por participar en actividades directamente relacionadas con el bienestiar de las personas.', 'Urbanismo, Ingenieria Civil, Sociología, Trabajo Social,Derecho, Enfermería y Obestetricia, Psicología, Pedagogía, Medicina, Odontología, Ciencias Politicas y Administración Pública, Economía, Relaciones Internacionales, Enseñanza de Inglés, Optometría, Planificación para el Desarrollo Agropecuario, Estudios Latinoamericanos, Bibliotecología y Estudios de la Información, Educación Musical.', 'A', 'A'),
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'EP' AND cat_area = 'A'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'EP' AND cat_area = 'A'), 'Agrado por planear, organizar o dirigir las actividades de personas o agrupaciones.', 'Actuaría, Economía, Administración, Ciencias Políticas y Administración Pública, Derecho, Ingeniería Industrial, Ingeniería de Alimentos, Ingeniería Petrolera, Psicología, Medicina, Relaciones Internacionales.', 'A', 'A'),
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'V' AND cat_area = 'A'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'V' AND cat_area = 'A'), 'Gusto por la lectura de obras diversas y satisfacción al expresarse verbalmente o por escrito.', 'Derecho, Ciencias de la Comunicación, Letras Clásicas, Lengua y Literaturas Modernas, Relaciones Internacionales, Literatura Dramática y Teatro, Sociología, Ciencias Políticas y Administración Pública.', 'A', 'A'),
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'AP' AND cat_area = 'A'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'AP' AND cat_area = 'A'), 'Agrado por conocer o realizar actividades creativas como dibujo, pintura, escultura, modelado.', 'Artes Visuales, Diseño y Comunicación Visual, Diseño Gráfico, Arquitectura, Arquitectura de Paisaje, Odontología, Literatura Dramática y Teatro.', 'A', 'A'),
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'MS' AND cat_area = 'A'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'MS' AND cat_area = 'A'), 'Gusto por la ejecución, estudio o  composición de la música.', 'Composición, Instrumentista, Canto, Etnomusicología, Piano, Educación Musical.', 'A', 'A'),
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'OG' AND cat_area = 'A'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'OG' AND cat_area = 'A'), 'Preferencia por actividades que requieren orden y sistematización.', 'Bibliotecología y Estudios de la Información, Actuaría, Matemáticas Aplicadas y Computación, Informática, Contaduría, Administración, Ciencias de la Comunicación, Matemáticas, Relaciones Internacionales, Economía, Ciencias Políticas y Administración Pública.', 'A', 'A'),
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'CI' AND cat_area = 'A'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'CI' AND cat_area = 'A'), 'Gusto por conocer o investigar la razón de ser de los fenómenos, las causas que los provocan y los principios que los explican.', 'Investiación Biomédica Básica, Ciencias Genómicas, Matemáticas, Física, Ingeniería Mecatrónica, Química, Biología, Psicología, Medicina Veterinaria y Zootecnia, Ingeniería Química, Química Farmacéutico- Biológica, Química Industrial, Química de Alimentos, Ingeniería en Alimentos, Filosofía, Historia.', 'A', 'A'),
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'CL' AND cat_area = 'A'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'CL' AND cat_area = 'A'), 'Gusto por resolver problemas de tipo cuantitativo, en donde intervienen las operaciones matemáticas.', 'Matemáticas, Economía, Contaduría,  Física, Ingenierías: Geológica, Geofísica, Civil, en Telecomunicaciones, Computación, Topográfica, Industrial, Química; Arquitectura, Geografía, Actuaría, Informática, Química, Matemáticas Aplicadas y Computación, Ciencias de la Comunicación.', 'A', 'A'),
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'MC' AND cat_area = 'A'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'MC' AND cat_area = 'A'), 'Atracción por armar, conocer o descubrir mecanismos por los cuales funciona un aparato y por proyectar y construir objetos diversos.', 'Ingenierías: Eléctrica - Electrónica, Geofísica, Topográfica, Civil, Petrolera, Mecánica Eléctrica, Química, en Computación, Mecánica, Química Metalúrgica, Mecatrónica, Arquitectura, Diseño Industrial.', 'A', 'A'),
(NULL, (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'DT' AND cat_area = 'A'), (SELECT cat_id FROM `prueba-vocacional`.`categorias` WHERE cat_tipo = 'DT' AND cat_area = 'A'), 'Satisfacción por actividades que se realizan en lugares abiertos, apartados de los conglomerados urbanos.', 'Biología, Ingeniería Agrícola, Ingeniería Geológica, Ingeniería Petrolera, Geografía, Ingeniería Civil, Ingeniería Topográfica y Geodésica, Medicina Veterinaria y Zootecnia, Planificación para el Desarrollo Agropecuario, Urbanismo.', 'A', 'A');

SET SQL_SAFE_UPDATES = 1;
